### ISSUE TITLE
Git folder packaged with node module

### ISSUE THREAD

**Issue by coolcom200** [FairVenturesLab/configuration-store-postgresql#1]
A git folder is included with the node module and causes installation errors
![image](https://user-images.githubusercontent.com/17069243/59721404-4b6a9c00-91ef-11e9-8a23-61d5b08b1154.png)
![image](https://user-images.githubusercontent.com/17069243/59721426-5ae9e500-91ef-11e9-9375-c37c606ea37d.png)

**Comment by smorrisfv** [comment]
Resolved by 1dc65606e3fdf568f264c5dfca8adcc73dacae9c.
